### ISSUE TITLE
BIP32-ED25519 questions and observations

### ISSUE THREAD

**Issue by evias** [nemtech/community#8]
Hello,

after researching the possibilities to implement an `extended key derivation algorithm` for catapult, it has resulted in several questions that I would like to be reviewed after a talk with @gimer. 

References:

- [Paper: Hierarchical Deterministic Keys over a Non-linear
Keyspace](https://cardanolaunch.com/assets/Ed25519_BIP.pdf)

- [Cardano Implementation Proposal in RUST](https://github.com/input-output-hk/rust-cardano/commit/5dd1416249128d7346028ef8cce713fd7bda0f28#diff-53e730e949d23c560003ed4730277013R242)

-- 

With these references I have come to research the implementation and only *one* point is left unclear to me. In following three links are three different `clamp bits` methods ; each of which I would like to understand the effects:

- Variant 1 `mk_ed25519_extended clamps` with 248, 63, 64: https://github.com/input-output-hk/rust-cardano/commit/5dd1416249128d7346028ef8cce713fd7bda0f28#diff-53e730e949d23c560003ed4730277013R242

- Variant 2 `normalize_bytes for XPrv, clamps` with 248, 31, 64 (written in binary): https://github.com/input-output-hk/rust-cardano/commit/5dd1416249128d7346028ef8cce713fd7bda0f28#diff-20f5bbac575dbd279d57a5959a3eb883R39

- Variant 3 `nem2-library clamps` with 248, 127, 64:  https://github.com/nemtech/nem2-library-js/blob/master/src/crypto/keyPair.js#L38

I understand the clamp bits for `a[0]` is to mask the bits as a security for small subgroup attacks. Can someone explain why `a[31]` gets clamped as well - furthermore, it gets clamped with 3 different values ? (63, 31, 127)

In *Variant 1* I understand the size of the `extended key` (`data`) is of 64 bytes and therefore `63` is used.
In *Variant 2* I understand the size the `private key` (`data`) is of 32 bytes and therefore `31` is used.
Following these information, I come to understand that in the *Variant 3* of our nem2-library, `127` is used because the `data` is in fact 128 bytes.

**Which effect does this clamping of bits has for `a[31]` ?**

Thank you :+1:

**Comment by gimer** [comment]
1. Clamping a[0] is not for a small subgroup attack.
2. bytes in a ed25519 key are in low-endian order (meaning a[0] is actually low-byte)
3. Clamping goes back to original Curve paper: http://cr.yp.to/ecdh/curve25519-20060209.pdf
4. Mind that the keyspace is not full 256 bits, but rather 251 bits (see 3)
5. In (3) key format is defined as follows:
![image](https://user-images.githubusercontent.com/6421169/56125004-37e54f80-5f78-11e9-990a-2a1ca9311147.png)

Now for the variants, mind that both variant 1 and variant 3 are equivalent:
Variant 1:
```
    extended_out[0] &= 248;
    extended_out[31] &= 63;
    extended_out[31] |= 64;
```
variant 3:
```
		h[0] &= 0xF8; // 248
		h[31] &= 0x7F; // 127
		h[31] |= 0x40; // 64
```

As for variant 2, it's described in cardano bip paper (section IV, point 2): 

> We admit only those ek such that the third highest bit of the last byte of kL is zero.

(they mean bit 253 here, `h[31] & 0x20 == 0`,  haven't went through whole paper, so not sure what is the reason for this requirement)
